name: app_ecom
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # iOS style icons.
  cupertino_icons: ^1.0.8

  # State Managemnet
  get: ^4.6.6

  # To Crousal Slider
  carousel_slider: ^5.0.0

  # To QR Scanner
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0

  # To local storage
  shared_preferences: ^2.3.3

  # To animation
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # assets

  assets:
    - assets/images/product_images/
    - assets/images/catogory/
    - assets/animation/
   
  # Local Fonts

  fonts:
    - family: Poppins,
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 300
    - family: OpenSans,
      fonts:
        - asset: assets/fonts/OpenSans.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
    - family: DancingScript,
      fonts:
        - asset: assets/fonts/DancingScript.ttf
          weight: 300
    - family: KodeMono,
      fonts:
        - asset: assets/fonts/KodeMono.ttf
          weight: 300
